############################################################################
##
## Config file related to bitbake
##
############################################################################

# include bitbake config
include conf/include/bitbake.inc

# include boot2qt config
include conf/include/boot2qt.inc

# include board config
include conf/include/board.inc

# include user config
include conf/include/user.inc

# include swupdate config
include conf/include/swupdate.inc
