############################################################################
##
## This file is part of the meta-embi layer.
##
############################################################################

# include boot2qt config
include conf/include/boot2qt.inc

# include rpi config
include conf/include/rpi.inc

# include user config
#include conf/include/user.inc

# include mender config
#include conf/include/mender.inc
